version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: arjun.yadav
      POSTGRES_PASSWORD: awesome_password
      POSTGRES_DB: test
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
